### ISSUE TITLE
Some ideas abouts bots:

### ISSUE THREAD

**Issue by wjxakioi** [rHanbowChic/NotePaper#1]
能考虑一下对于机械性的访问/QPS过高的直接CloudFlare开杀吗？                 
或者对单IP开流量限制                         
_~~完全没必要对所有脚本进行支持，让那些破坏者自己想法子~~_                 

Consider using CloudFlare for mechanical access/excessive QPS?                 
Or set a limit for individual IPs.                         
_~~There's no need to support all scripts, let the vandals think for themselves(and their behaviours)~~_.

**Comment by rHanbowChic** [comment]
这不是NotePaper项目的issue。它和note.ect.fyi有关，一个搭载NotePaper的服务器。
请向我发送[Email](mailto:ect@vivaldi.net)讨论note.ect.fyi的事宜。

（不过就这个问题，我会加入IP访问速率限制。）

**Comment by wjxakioi** [comment]
我在这里指的不是note.ect.fyi，            
而是说，对于这种能让服务器宕机的东西，给它加一个限制。             

~~就是拖进localhost试一下脚本，然后玩没了~~

**Comment by rHanbowChic** [comment]
经过测试，确定`get_db().commit()`对压力测试下的响应速度影响最大。我会对这一点进行优化！

限制不是NotePaper需要实现的，因为CloudFlare等反向代理服务完全可以做到这一点。管理员可以自由选择。

**Comment by rHanbowChic** [comment]
已经优化高负载下的响应速度。
现在可以处理每秒2000次以上的的POST请求，同时对浏览器用户的响应速度无任何体感上的影响。具体上限不明，因为我没有实验。
对于Rate Limiting，可以使用Nginx反向代理做到这一点。这不是NotePaper在应用层面上需要实现的功能。
