### ISSUE TITLE
建议使用http post更新页面时也向socket.io房间广播变更

### ISSUE THREAD

**Issue by defaultuser8848** [rHanbowChic/NotePaper#3]
这样可以减轻上层应用开发者的负担，同时避免不同步的情况。

**Comment by rHanbowChic** [comment]
当前的设计有助于缓解脚本覆盖的问题----如果每次POST请求都导致页面内容随即更新，可能会遇到写到一半没有保存，页面整个消失的突发情况。
这并非没有考虑过的情况。

**Comment by defaultuser8848** [comment]
> 当前的设计有助于缓解脚本覆盖的问题----如果每次POST请求都导致页面内容随即更新，可能会遇到写到一半没有保存，页面整个消失的突发情况。 这并非没有考虑过的情况。

我不尽认同。
第一，毕竟现在前后端都是开源的，破坏者只要稍微找一下就能发现sio的覆盖API，这样也会直接没，所以现在的做法是杯水车薪，再者，将内容在本地编辑好再粘贴到页面上应该是一个类note网站用户的基本技能，现在这样做没有什么意义；第二，如果允许更新页面的话，开发上层应用时可以更好的地进行实时检测和通讯，而不是使用短轮询，这样有助于反破坏（虽然说破坏者也可能利用这个特性，但是这样做至少可以增加反抗的可能）；第三，如果保持现在这样的话，用户无法和使用轮询工作的脚本正常交互。

另外顺便建议通过一个配置控制是否允许sio更新时使用`pass`参数。

**Comment by rHanbowChic** [comment]
考虑到现在已经有基于Socket.IO的脚本出现，对POST请求的单方面限制已无实际意义。
已在 Commit 3b973f3 为POST请求添加Socket.IO文本更新。
